### ISSUE TITLE
Typo in documentation?

### ISSUE THREAD

**Issue by gardner** [GovTech-CSG/govtech-csg-xcg-securefileupload#2]
It appears there may be a typo in the [documentation](https://xcg.tech.gov.sg/packages/securefileupload/).

Consider `validator` vs `validators`:

```diff
-    cover_photo = models.ImageField(upload_to="uploads/", validator=[xcg_file_validator])
+    cover_photo = models.ImageField(upload_to="uploads/", validators=[xcg_file_validator])
```

**Comment by yyin119** [comment]
Hi @gardner, thanks for pointing this out. I've fixed the documentation - will close this issue once you verify the fix :)

**Comment by gardner** [comment]
Thank you!
